-- =========================================================
-- Migration 0004: Gold analytical artifact registry
-- =========================================================
--
-- Records the physical artifacts produced by a logical Gold run.
--
-- A Gold run may publish multiple artifacts:
--   - BASE: analytics-ready detailed dataset
--   - MART: analytical aggregate generated by the Gold planner
--
-- The unique constraint on (gold_run_id, artifact_name) allows
-- deterministic publication/recovery without creating duplicate
-- artifact metadata for the same logical Gold run.
-- =========================================================

CREATE TABLE IF NOT EXISTS gold_artifacts (
    gold_artifact_id BIGSERIAL PRIMARY KEY,

    gold_run_id BIGINT NOT NULL,

    artifact_type VARCHAR NOT NULL,

    artifact_name VARCHAR NOT NULL,

    storage_path TEXT NOT NULL,

    row_count BIGINT NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_gold_artifacts_gold_run
        FOREIGN KEY (gold_run_id)
        REFERENCES gold_runs(gold_run_id),

    CONSTRAINT uq_gold_artifact_run_name
        UNIQUE (gold_run_id, artifact_name),

    CONSTRAINT chk_gold_artifacts_type
        CHECK (
            artifact_type IN (
                'BASE',
                'MART'
            )
        ),

    CONSTRAINT chk_gold_artifacts_row_count
        CHECK (row_count >= 0)
);


CREATE INDEX IF NOT EXISTS idx_gold_artifacts_gold_run_id
    ON gold_artifacts(gold_run_id);


CREATE INDEX IF NOT EXISTS idx_gold_artifacts_type
    ON gold_artifacts(artifact_type);