// Run with: node tests/contracts.cjs (uses the existing TypeScript dependency).
const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => {
  module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS },
  }).outputText, filename)
}
const { createInitialContract, validateContract } = require('../src/features/datasets/contracts/validation.ts')
const { getDatasetContract, saveDatasetContract, contractStorageKey } = require('../src/features/datasets/contracts/storage.ts')
const { compareSchema } = require('../src/features/datasets/contracts/schemaMatch.ts')
const { acceptDatasetFile, readDatasetFiles } = require('../src/features/files/data/storage.ts')
const { inspectCsv } = require('../src/features/files/utils/inspectCsv.ts')
const values = new Map()
global.localStorage = { getItem: (key) => values.get(key) ?? null, setItem: (key, value) => values.set(key, value) }
global.window = new EventTarget()

async function run() {
  const inspection = await inspectCsv(new File(['id,name,created\n1,Alice,2026-10-04'], 'customers.csv'))
  const initial = createInitialContract('1', '99', 'Customers', inspection.columns)
  assert.deepEqual(initial.columns.map((column) => column.name), inspection.columns)
  assert.ok(initial.columns.every((column) => column.dataType === 'STRING' && !column.required))
  assert.deepEqual(initial.primaryKey, [])
  assert.equal(initial.loadMode, 'APPEND')
  assert.equal(validateContract(initial), null)
  assert.equal(compareSchema(inspection.columns).status, 'NO_CONTRACT')
  assert.ok(validateContract({ ...initial, columns: [] }))
  assert.ok(validateContract({ ...initial, columns: [...initial.columns, { name: 'ID', dataType: 'STRING', required: false }] }))
  assert.ok(validateContract({ ...initial, columns: [{ name: '', dataType: 'STRING', required: false }] }))
  assert.ok(validateContract({ ...initial, loadMode: 'UPSERT' }))
  assert.ok(validateContract({ ...initial, primaryKey: ['id'] }))
  const configured = { ...initial, columns: initial.columns.map((column) => ({ ...column, required: column.name === 'id', dataType: column.name === 'created' ? 'DATETIME' : 'STRING' })), primaryKey: ['id'], loadMode: 'UPSERT' }
  assert.equal(validateContract(configured), null)
  assert.ok(validateContract({ ...configured, primaryKey: ['id', 'ID'] }))
  assert.ok(validateContract({ ...configured, primaryKey: ['missing'] }))
  assert.ok(validateContract({ ...configured, schemaEvolutionPolicy: 'UNKNOWN' }))
  assert.ok(validateContract({ ...initial, loadMode: 'SNAPSHOT' }))
  assert.equal(validateContract({ ...configured, loadMode: 'SNAPSHOT' }), null)
  let changed = 0
  window.addEventListener('datarise-contract-changed', () => changed++)
  saveDatasetContract('1', '99', configured)
  assert.equal(changed, 1)
  assert.deepEqual(getDatasetContract('1', '99'), configured)
  assert.equal(getDatasetContract('2', '99'), undefined)
  assert.equal(getDatasetContract('1', '100'), undefined)
  assert.throws(() => saveDatasetContract('2', '99', configured))
  assert.throws(() => saveDatasetContract('1', '100', configured))
  assert.equal(readDatasetFiles('1', '99').length, 0, 'Saving a contract must not accept a file')
  const saved = getDatasetContract('1', '99')
  assert.equal(compareSchema(inspection.columns, saved).status, 'MATCH')
  assert.equal(compareSchema([...inspection.columns, 'extra'], saved).status, 'WARNING')
  assert.equal(compareSchema(['name', 'created'], saved).status, 'BREAKING')
  assert.equal(compareSchema(['unrelated', 'other'], saved).status, 'WRONG_DATASET_LIKELY')
  saveDatasetContract('1', '99', { ...saved, schemaEvolutionPolicy: 'STRICT' })
  assert.equal(compareSchema([...inspection.columns, 'extra'], getDatasetContract('1', '99')).status, 'BREAKING')
  assert.equal(getDatasetContract('1', '99').columns.length, 3, 'Later CSVs never extend the contract')
  acceptDatasetFile('1', '99', inspection, 'accepted-selection')
  acceptDatasetFile('1', '99', inspection, 'accepted-selection')
  assert.equal(readDatasetFiles('1', '99').length, 1)
  assert.equal(readDatasetFiles('1', '99')[0].status, 'READY_TO_PROCESS')
  assert.equal(readDatasetFiles('1', '99')[0].batchId, undefined)
  assert.equal(readDatasetFiles('2', '99').length, 0)
  const { workspaceId, schemaEvolutionPolicy, ...legacy } = initial
  assert.equal(workspaceId, 1); assert.equal(schemaEvolutionPolicy, 'ALLOW_ADDITIVE')
  values.set(contractStorageKey('1', '99'), JSON.stringify(legacy))
  assert.equal(getDatasetContract('1', '99').workspaceId, 1)
  assert.equal(getDatasetContract('1', '99').schemaEvolutionPolicy, 'ALLOW_ADDITIVE')
  values.set(contractStorageKey('2', '99'), JSON.stringify(configured))
  assert.throws(() => getDatasetContract('2', '99'), /different workspace/)
  values.set(contractStorageKey('1', '99'), '{}')
  assert.throws(() => getDatasetContract('1', '99'))
  localStorage.setItem = () => { throw new Error('Storage quota exceeded') }
  assert.throws(() => saveDatasetContract('1', '99', initial), /quota/)
  console.log('Contract defaults, validation, ownership, legacy compatibility, schema policies, change events, and Phase 1.1 persistence checks passed.')
}
run().catch((error) => { console.error(error); process.exitCode = 1 })
