// Reuse the existing lightweight SSR harness; no additional test framework.
require('./incremental.cjs')
const assert = require('node:assert/strict'), React = require('react')
const {renderToStaticMarkup} = require('react-dom/server')
const {MemoryRouter} = require('react-router-dom')
const resource = require('../src/services/api/useApiResource.ts')
const {IncrementalPolicy} = require('../src/features/datasets/contracts/components/IncrementalPolicy.tsx')
const {ProcessingResult} = require('../src/features/ingestion/components/ProcessingResult.tsx')
const {SnapshotDelivery} = require('../src/features/ingestion/components/SnapshotDelivery.tsx')
const render = element => renderToStaticMarkup(React.createElement(MemoryRouter,null,element))
const p={policy_id:1,dataset_id:20,dataset_version_id:7,policy_version:1,load_strategy:'SNAPSHOT',business_keys:['customer_id'],schema_evolution_policy:'STRICT',event_time_column:null,snapshot_coverage:'COMPLETE'}
resource.useApiResource=()=>({data:{workspace_id:10,dataset_id:20,schema_versions:[],policies:[p],applications:[],current_state:{state_id:1,policy_id:1,row_count:4,active_rows:3,inactive_rows:1,snapshot_boundary_at:'2026-10-06T00:00:00Z',state_analytics_status:'STALE'}},retry:()=>{}})
let html=render(React.createElement(IncrementalPolicy,{workspaceId:'10',datasetId:'20'}))
for (const text of ['Complete snapshot','customer_id','Active records','Inactive records','Latest trusted snapshot','Records missing from this delivery may be marked inactive.','Analytics refresh required','disabled=""']) assert.ok(html.includes(text),text)
const context={upload_request_id:11,load_strategy:'SNAPSHOT',load_policy:p,status:'SUCCESS_WITH_WARNINGS',stages:{bronze:'SUCCESS',rules:'FINALIZED',silver:'SUCCESS',dataset_update:'SUCCESS',gold:'SUCCESS'},issue_summary:[],snapshot_context:{coverage:'PARTIAL',delivery_kind:'BACKFILL',effective_at:'2026-09-01T00:00:00Z'},snapshot_outcome:'STALE',deactivated_rows:0,reactivated_rows:1,active_rows:3,inactive_rows:1,stale_rows:2}
html=render(React.createElement(ProcessingResult,{context}))
for (const text of ['Partial / unknown','Missing records will not be deactivated','Reactivated','Active records','Inactive records','Older snapshot detected','retained for history']) assert.ok(html.includes(text),text)
assert.ok(!html.includes('deleted'))
html=render(React.createElement(SnapshotDelivery,{workspaceId:'10',datasetId:'20',context:{...context,snapshot_context:null,application:null},reload:()=>{},disabled:false}))
assert.ok(html.includes('Choose coverage') && html.includes('Complete snapshot') && html.includes('explicit timezone') && html.includes('Correction') && html.includes('Backfill'))
assert.ok(html.includes('disabled=""'))
html=render(React.createElement(SnapshotDelivery,{workspaceId:'10',datasetId:'20',context:{...context,snapshot_context:null,load_policy:{...p,snapshot_coverage:'PARTIAL'}},reload:()=>{},disabled:false}))
assert.ok(!html.includes('<option value="COMPLETE">'))
console.log('SNAPSHOT policy, declarations, partial/stale notices, lifecycle metrics and policy lock SSR checks passed')
